backend:
  name: git-gateway
  branch: hugo # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    format: 'frontmatter'
    extension: 'md'
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default:
           - api
           - babel
           - cli
           - confluent
           - css-in-js
           - design-systems
           - digitalocean
           - docker
           - emacs
           - emotion
           - french
           - gatsby
           - gke
           - go
           - golang
           - graphql
           - hugo
           - javascript
           - kafka
           - kubernetes
           - preact
           - prettier
           - productivity
           - react
           - rocket-league
           - stacks
           - static
           - tooling
           - vpn
           - zookeeper
      - {label: "Body", name: "body", widget: "markdown"}
